
import { VehicleConfig } from "../types";

export const generateRobotHeader = (config: VehicleConfig): string => {
  const timestamp = new Date().toISOString();
  
  let code = `/**
 * robot_config.h
 * Auto-generated by Arduino Web Sim
 * Timestamp: ${timestamp}
 */

#pragma once
#include <Arduino.h>

// --- Robot Metadata ---
#define ROBOT_NAME "SimRobot"

// --- Motors ---
enum MotorRole {
  MOTOR_ROLE_LEFT,
  MOTOR_ROLE_RIGHT,
  MOTOR_ROLE_OMNI,
  MOTOR_ROLE_CUSTOM
};

struct MotorDef {
  const char* name;
  MotorRole role;
  uint8_t pwmPin;
  int8_t dirPin;
  float maxSpeed; // m/s
};

const uint8_t NUM_MOTORS = ${config.motors.length};
const MotorDef MOTORS[] = {
`;

  // Generate Motors
  config.motors.forEach((m, i) => {
    const roleMap: Record<string, string> = {
      'left': 'MOTOR_ROLE_LEFT',
      'right': 'MOTOR_ROLE_RIGHT',
      'omni': 'MOTOR_ROLE_OMNI',
      'custom': 'MOTOR_ROLE_CUSTOM'
    };
    code += `  { "${m.name}", ${roleMap[m.role]}, ${m.pwmPin}, ${m.dirPin}, ${m.maxSpeed.toFixed(2)}f }${i < config.motors.length - 1 ? ',' : ''}\n`;
  });

  code += `};

// --- Servos ---
struct ServoDef {
  const char* name;
  uint8_t pin;
  float minAngle;
  float maxAngle;
};

const uint8_t NUM_SERVOS = ${config.servos.length};
const ServoDef SERVOS[] = {
`;

  // Generate Servos
  config.servos.forEach((s, i) => {
    code += `  { "${s.name}", ${s.pin}, ${s.minAngle.toFixed(1)}f, ${s.maxAngle.toFixed(1)}f }${i < config.servos.length - 1 ? ',' : ''}\n`;
  });

  code += `};

// --- Sensors ---
enum SensorType {
  SENSOR_ULTRASONIC,
  SENSOR_LINE,
  SENSOR_IMU
};

struct SensorDef {
  const char* name;
  const char* channel;
  SensorType type;
  // Pin mapping (simplified)
  uint8_t pin1; // Trigger / Analog / SDA
  uint8_t pin2; // Echo / SCL
};

const uint8_t NUM_SENSORS = ${config.sensors.length};
const SensorDef SENSORS[] = {
`;

  // Generate Sensors
  config.sensors.forEach((s, i) => {
    let typeEnum = 'SENSOR_ULTRASONIC';
    if (s.type === 'line') typeEnum = 'SENSOR_LINE';
    if (s.type === 'impact') typeEnum = 'SENSOR_IMU';

    const p1 = s.pins.trigger ?? s.pins.analog ?? 0;
    const p2 = s.pins.echo ?? 0;

    code += `  { "${s.name}", "${s.channel}", ${typeEnum}, ${p1}, ${p2} }${i < config.sensors.length - 1 ? ',' : ''}\n`;
  });

  code += `};

// --- Convenience Macros ---
`;

  // Generate Defines for easy access
  config.motors.forEach(m => {
     if(m.pwmPin !== undefined) code += `#define PIN_${m.name.toUpperCase().replace(/\s/g, '_')} ${m.pwmPin}\n`;
  });
  config.servos.forEach(s => {
     code += `#define PIN_${s.name.toUpperCase().replace(/\s/g, '_')} ${s.pin}\n`;
  });
  config.sensors.forEach(s => {
     code += `#define CHANNEL_${s.channel} "${s.channel}"\n`;
     if (s.pins.analog) code += `#define PIN_${s.channel} ${s.pins.analog}\n`;
     else if (s.pins.trigger) code += `#define PIN_${s.channel}_TRIG ${s.pins.trigger}\n`;
  });

  return code;
};
