import json
import glob
import numpy as np
import os
import argparse
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

def load_data(demo_files):
    all_obs = []
    all_actions = []
    
    for fname in demo_files:
        print(f"Loading {fname}...")
        with open(fname, 'r') as f:
            data = json.load(f)
            for sample in data['samples']:
                # Flatten obs if needed, but it should be a list already
                all_obs.append(sample['obs'])
                all_actions.append(sample['action'])
                
    return np.array(all_obs), np.array(all_actions)

def export_to_cpp(model, scaler, mean_obs, std_obs, filename="learned_policy_imit.h", func_name="policy_imit_eval", metadata=None):
    # Scikit-learn MLPRegressor attributes:
    # coefs_: list of weight matrices [input->h1, h1->h2, ..., hn->output]
    # intercepts_: list of bias vectors
    
    print(f"Exporting to {filename}...")
    
    # We assume a specific architecture for the C++ static arrays
    # For flexibility, we will perform a dynamic generation or assert 2 hidden layers.
    # The prompt example used: Input -> H1 -> H2 -> Output
    
    weights = model.coefs_
    biases = model.intercepts_
    
    n_layers = len(weights)
    print(f"Detected {n_layers} weight matrices (implies {n_layers - 1} hidden layers).")
    
    # Get dimensions
    input_dim = weights[0].shape[0]
    output_dim = weights[-1].shape[1]
    
    with open(filename, 'w') as f:
        f.write("#pragma once\n\n")
        f.write(f"// Generated by train_policy.py\n")
        f.write("#include <math.h>\n\n")
        
        f.write(f"#define POLICY_INPUT_DIM   {input_dim}\n")
        f.write(f"#define POLICY_OUTPUT_DIM  {output_dim}\n")
        
        if metadata:
            if "expected_num_sensors" in metadata:
                 f.write(f"#define EXPECTED_NUM_SENSORS {metadata['expected_num_sensors']}\n")
        
        f.write("\n")
        
        # Dimensions macros
        for i, w in enumerate(weights):
             # w shape is [dim_in, dim_out] (sklearn format is inputs x units)
             # C++ implementation usually expects [units][inputs] for easier loops?
             # Or we stick to the format.
             # Prompt Example: POLICY_W1[POLICY_H1_DIM][POLICY_INPUT_DIM]
             # This implies rows=units, cols=inputs.
             # Sklearn is rows=inputs, cols=units. We need to TRANSPOSE.
             
             layer_name = f"H{i+1}" if i < n_layers - 1 else "OUTPUT"
             prev_name = f"H{i}" if i > 0 else "OBS"
             
             dim_in = w.shape[0]
             dim_out = w.shape[1]
             
             # We can define dims if we want
             if i < n_layers - 1:
                 f.write(f"#define POLICY_H{i+1}_DIM {dim_out}\n")
        
        f.write("\n")
        
        # 1. Normalization Constants
        f.write(f"const float POLICY_OBS_MEAN[{input_dim}] = {{")
        f.write(", ".join(f"{x:.6f}f" for x in mean_obs))
        f.write("};\n")
        
        f.write(f"const float POLICY_OBS_STD[{input_dim}] = {{")
        f.write(", ".join(f"{x:.6f}f" for x in std_obs))
        f.write("};\n\n")

        # 2. Weights and Biases
        for i, (w, b) in enumerate(zip(weights, biases)):
            layer_idx = i + 1
            w_T = w.T # Transpose to [units, inputs]
            
            rows, cols = w_T.shape
            
            f.write(f"// Layer {layer_idx} Weights [{rows}][{cols}]\n")
            f.write(f"const float POLICY_W{layer_idx}[{rows}][{cols}] = {{\n")
            for row in w_T:
                f.write("  { " + ", ".join(f"{x:.6f}f" for x in row) + " },\n")
            f.write("};\n\n")
            
            f.write(f"// Layer {layer_idx} Biases [{rows}]\n")
            f.write(f"const float POLICY_B{layer_idx}[{rows}] = {{")
            f.write(", ".join(f"{x:.6f}f" for x in b))
            f.write("};\n\n")

        # 3. Inference Function
        # We generate a specialized function hardcoded for 2 hidden layers as requested, 
        # or generic if easy. Let's stick to the prompt's 2-hidden-layer example for API compatibility.
        # But wait, if sklearn chooses different layers?
        # We will assume fixed architecture for the C++ function 'policy_imit_eval'.
        
        f.write("// Inference function (Hardcoded for 2 hidden layers for now, matching the defines)\n")
        f.write(f"void {func_name}(const float* obs_raw, float* out) {{\n")
        f.write(f"  float obs[{input_dim}];\n")
        
        # Checking layer counts
        if n_layers == 3: # Input -> H1 -> H2 -> Output
             h1_dim = weights[0].shape[1]
             h2_dim = weights[1].shape[1]
             
             f.write(f"  float h1[{h1_dim}];\n")
             f.write(f"  float h2[{h2_dim}];\n\n")
             
             # Normalize
             f.write(f"  for (int i = 0; i < {input_dim}; ++i) {{\n")
             f.write(f"    obs[i] = (obs_raw[i] - POLICY_OBS_MEAN[i]) / POLICY_OBS_STD[i];\n")
             f.write("  }\n\n")
             
             # L1
             f.write(f"  for (int i = 0; i < {h1_dim}; ++i) {{\n")
             f.write(f"    float sum = POLICY_B1[i];\n")
             f.write(f"    for (int j = 0; j < {input_dim}; ++j) {{\n")
             f.write("      sum += POLICY_W1[i][j] * obs[j];\n")
             f.write("    }\n")
             f.write("    h1[i] = tanhf(sum);\n")
             f.write("  }\n\n")
             
             # L2
             f.write(f"  for (int i = 0; i < {h2_dim}; ++i) {{\n")
             f.write(f"    float sum = POLICY_B2[i];\n")
             f.write(f"    for (int j = 0; j < {h1_dim}; ++j) {{\n")
             f.write("      sum += POLICY_W2[i][j] * h1[j];\n")
             f.write("    }\n")
             f.write("    h2[i] = tanhf(sum);\n")
             f.write("  }\n\n")
             
             # Out
             f.write(f"  for (int i = 0; i < {output_dim}; ++i) {{\n")
             f.write(f"    float sum = POLICY_B3[i];\n")
             f.write(f"    for (int j = 0; j < {h2_dim}; ++j) {{\n")
             f.write("      sum += POLICY_W3[i][j] * h2[j];\n")
             f.write("    }\n")
             f.write("    out[i] = tanhf(sum);\n")
             f.write("  }\n")
             
        else:
            f.write("  // Error: The python script trained a model with different topology than the C++ template expects.\n")
            
        f.write("}\n")

def export_to_json(model, mean_obs, std_obs, filename="learned_policy_weights.json", metadata=None):
    # Create a dictionary structure compatible with TS loading
    weights_list = [w.T.tolist() for w in model.coefs_] # Transpose for TS too if we use row-major multiplication
    biases_list = [b.tolist() for b in model.intercepts_]
    
    export_obj = {
        "mean": mean_obs.tolist(),
        "std": std_obs.tolist(),
        "weights": weights_list,
        "biases": biases_list,
        "activations": ["tanh", "tanh", "tanh"] # simplified
    }
    
    if metadata:
        export_obj.update(metadata)
    
    with open(filename, 'w') as f:
        json.dump(export_obj, f, indent=2)
    print(f"Exported JSON to {filename}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # Default to 'data' subdir relative to this script
    default_data_dir = os.path.join(os.path.dirname(__file__), "data")
    parser.add_argument("--demo_dir", type=str, default=default_data_dir, help="Directory containing .json recordings")
    parser.add_argument("--out_h", type=str, default="learned_policy_imit.h")
    parser.add_argument("--out_json", type=str, default="learned_policy_weights.json")
    args = parser.parse_args()
    
    files = glob.glob(os.path.join(args.demo_dir, "demo_*.json"))
    if not files:
        print("No demo files found!")
        exit(1)
        
    X, y = load_data(files)
    print(f"Dataset shape: X={X.shape}, y={y.shape}")
    
    # Normalize inputs
    scaler = StandardScaler()
    X_norm = scaler.fit_transform(X)
    
    # Train
    # Using small architecture as requested: 16, 8
    print("Training MLP...")
    regr = MLPRegressor(hidden_layer_sizes=(16, 8), activation='tanh', max_iter=2000, random_state=42)
    regr.fit(X_norm, y)
    
    print("Training score:", regr.score(X_norm, y))
    
    export_to_cpp(regr, scaler, scaler.mean_, scaler.scale_, filename=args.out_h)
    export_to_json(regr, scaler.mean_, scaler.scale_, filename=args.out_json)
    
